# File configuration for user data privacy

user:
  id: "string"
  name: "string"
  email: "string"
  phone: "string"
  password: "string"
  address:
    street: "string"
    city: "string"
    state: "string"
    postal_code: "string"
    country: "string"


order:
  id: "string"
  user_id: "string"
  items:
    -product_id: "string"
    quantity: "number"
  total_price: "number
  status: "string"
  shipping_details:
    address:
      street: "string"
      city: "string"
      state: "string"
      postal_code: "string"
      country: "string"
    method: "string"
    estimated_delivery_date: "string"

# Security measures for data protection
securit:
  session_storage: "encrypted"
  transit_encryption: "TLS 1.3"
  data_encryption: "AES-256"
  access_control: "rol-based"
  compliance:
    - GDPR
    - CCPA